payment/urls.py
from django.urls import path
from .views import completePayment

app_name = 'payment'
urlpatterns = [
    path('paymentstatus/', completePayment, name='completePayment'),
]

server/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/auth/', include('users.urls')),
    path('api/location/', include('locations.urls')),
    path('api/ticket/', include('tickets.urls')),
    path('api/payment/', include('payment.urls')),
]

tickets/urls.py
from django.urls import path
from .views import bookTicket, book_Ticket, index

app_name = 'ticket'

urlpatterns = [
    path('bookticket/', bookTicket, name='bookTicket'),
    path('bookticket/<int:locationID>/', book_Ticket, name='book_Ticket'),
    path('', index, name='index')
]

users/urls.py
from django.urls import path

from .views import (login, logout, private, refresh, register, reset_password,
                    resetpasssord, test)

urlpatterns = [
    path('login/', login),
    path('register/', register),
    path('private/', private),
    path('refresh/', refresh),
    path('reset/<str:token>/<int:userId>/', reset_password),
    path('resetPassword/', resetpasssord),
    path('logout/', logout),
    path('test/<int:testNo>/', test),
]

payment/models.py
import uuid
from django.db import models
from tickets.models import Ticket

# Create your models here.


class Payment(models.Model):
    payment_request_id = models.CharField(max_length=150)
    payment_id = models.CharField(max_length=150)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    response = models.TextField()

    def __str__(self) -> str:
        return str(self.id)

tickets/models.py
from django.db import models
from users.models import User
from locations.models import Location
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.


class Ticket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    date = models.DateField(null=False)
    quantity = models.IntegerField(default=1, null=False, validators=[
        MaxValueValidator(6),
        MinValueValidator(1)
    ]
    )
    amount = models.IntegerField(default=0)
    payment_id = models.CharField(
        max_length=100)
    paid = models.BooleanField(default=False)

    def __str__(self) -> str:
        return (str(self.id)+"_"+self.user.username+"_"+self.location.name+"_"+str(self.paid))

payment/views.py
from django.shortcuts import render
from rest_framework.response import Response
from django.views.decorators.csrf import csrf_exempt
from rest_framework.decorators import api_view
from .models import Payment
from django.http import HttpResponse
from tickets.models import Ticket
from instamojo_wrapper import Instamojo
from django.conf import settings
import cloudinary
import cloudinary.uploader
import cloudinary.api
from .serializers import PaymentSerializer
# from users.utils import send_qrcode

from django.core.mail import send_mail
from django.template.loader import render_to_string
# Create your views here.

# app_name = "payment"

# Completing the payment request,saving a Payment instance and sending a email with QR code


@api_view(['GET'])
def completePayment(request):
    try:
        ticket = Ticket.objects.get(
            payment_id=request.GET.get('payment_request_id'))
        data = {
            'payment_request_id': request.GET.get('payment_request_id'),
            'payment_status': request.GET.get('payment_status'),
            'payment_id': request.GET.get('payment_id'),
            'ticket': ticket.pk,
        }
    except Exception as e:
        return Response({
            'detail': 'Problem with ticket querying -> '+str(e)
        }, status=400)

    payment_object = PaymentSerializer(data=data)

    if payment_object.is_valid():
       # Creating a client to verify payment request.
        data['ticket'] = Ticket.objects.get(pk=data['ticket'])
        try:
            client = Instamojo(api_key=settings.API_KEY,
                               auth_token=settings.AUTH_TOKEN,
                               endpoint='https://test.instamojo.com/api/1.1/')
            response = client.payment_request_payment_status(
                data['payment_request_id'], data['payment_id'])
            print(response)
        except Exception as e:
            return Response({
                'detail': "Payment problem ->" + str(e)
            }, status=500)

        # Checking if payment has been successfully completed
        if (data['payment_status'] == 'Credit' and response['payment_request']['status'] == 'Completed'):
            try:
                data['ticket'].paid = True
                data['ticket'].save()
                payment = Payment(payment_request_id=data['payment_request_id'],
                                  payment_id=data['payment_id'], ticket=data['ticket'], response=response)
                payment.save()
            except Exception as e:
                return Response({
                    'detail': str(e)
                }, status=500)

            user = data['ticket'].user

            config = cloudinary.config(secure=True)

            # Creating a payment response for QRcode
            payment_response = {
                'id': str(payment.id),
                # 'user_id': user.id,
                # 'ticket_id': ticket.id,
                # 'quantity': ticket.quantity,
                # 'order_id': payment_request_id,
                # 'payment_id': payment_id,
            }

            # Using a API for QR code generation
            link = "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=" + \
                str(payment_response)

            # Sending a mail
            try:
                msg_plain = render_to_string('email.txt')
                msg_html = render_to_string(
                    'confirmationEmail.html', {'date': data['ticket'].date, 'location': data['ticket'].location, 'link': link})

                send_mail("Confirmation email",
                          msg_plain,
                          settings.EMAIL_HOST_USER,
                          [user.email],
                          html_message=msg_html)
            except Exception as e:
                return Response({
                    'detail': 'Problem with the email service -> ' + str(e)
                }, status=503)

            # Rendering successfull payment page
            return render(request, 'success.html')
        else:
            return HttpResponse("Some error occured. Payment not successful any money deducted will be refunded within 5 to 7 days")
    else:
        return Response({
            'detail': payment_object.errors
        }, status=500)

tickets/views.py
from django.shortcuts import render
import jwt
from rest_framework.response import Response
from rest_framework.decorators import api_view
from users.models import User
from locations.models import Location
from .serializers import TicketSerializer
from .models import Ticket
from users.decorators import login_required
from django.conf import settings
from django.core.serializers.json import DjangoJSONEncoder
from django.http import HttpRequest
import json

# Create your views here.
from instamojo_wrapper import Instamojo

# remove GET request


@api_view(['GET', 'POST'])
@login_required
def bookTicket(request):
    if request.method == "POST":
        try:
            # user = User.objects.get(username=request.POST.get('user'))
            user = request.user

            location = Location.objects.get(name=request.POST.get('location'))
            data = ({
                'user': user.pk,
                'location': location.pk,
                'date': request.POST.get('date'),
                'quantity': request.POST.get('quantity'),
                'amount': request.POST.get('amount'),
            })
        except jwt.ExpiredSignatureError:
            return Response({
                'detail': "Access token expired."
            }, status=403)
        except Exception as e:
            return Response({
                'detail': str(e)
            }, status=500)

        ticket = TicketSerializer(data=data)
        if ticket.is_valid():
            # Getting all the items from the frontend after validation
            data = ({
                'user': user,
                'location': location,
                'date': data['date'],
                'quantity': data['quantity'],
                'amount': data['amount'],
            })
            print(data['amount'], " ", data['user'])

            try:
                # Creating Instamojo Client and Order id
                client = Instamojo(api_key=settings.API_KEY, auth_token=settings.AUTH_TOKEN,
                                   endpoint='https://test.instamojo.com/api/1.1/')
                print(HttpRequest.get_full_path)
                redirect_url = str(
                    "https://" + str(HttpRequest.get_host(request)) + "/api/payment/paymentstatus/")

                # redirect_url = str(
                #     HttpRequest.get_full_path + "/api/payment/paymentstatus/")

                payment_response = client.payment_request_create(
                    amount=data['amount'],
                    purpose='Buying a ticket',
                    buyer_name=data['user'].username,
                    email=data['user'].email,
                    send_email=True,
                    redirect_url=redirect_url,
                    allow_repeated_payments=False,
                )
                print(payment_response)
                order_id = payment_response['payment_request']['id']
                tempTicket = Ticket.objects.get_or_create(user=data['user'], location=data['location'],
                                                          date=data['date'], quantity=data['quantity'], amount=data['amount'], payment_id=order_id)
            except Exception as e:
                return Response({
                    'detail': str(e)
                }, status=500)

            return Response({
                'detail': "Successfully payment link generated.",
                'link': payment_response['payment_request']['longurl'],
            }, status=200)
            # return render(request, 'form.html', {'payment_url': payment_response['payment_request']['longurl'], 'button': "hide-button", 'field': "disable-field"})

        return Response({
            'detail': ticket.errors
        }, status=400)
    else:
        return Response({
            'status': False
        })


@login_required
@api_view(['POST'])
def book_Ticket(request, locationID):
    if request.method == "POST":
        try:
            user = User.objects.get(username=request.POST.get('user'))
            location = Location.objects.get(name=request.POST.get('location'))
            data = ({
                'user': user.pk,
                'location': location.pk,
                'date': request.POST.get('date'),
                'quantity': request.POST.get('quantity'),
                'amount': request.POST.get('amount'),
            })
        except Exception as e:
            return Response({
                'detail': str(e)
            }, status=400)

        ticket = TicketSerializer(data=data)
        if ticket.is_valid():
            # Getting all the items from the frontend after validation
            data = ({
                'user': user,
                'location': location,
                'date': data['date'],
                'quantity': data['quantity'],
                'amount': data['amount'],
            })
            print(data['amount'], " ", data['user'])

            try:
                # Creating Instamojo Client and Order id
                client = Instamojo(api_key=settings.API_KEY, auth_token=settings.AUTH_TOKEN,
                                   endpoint='https://test.instamojo.com/api/1.1/')

                redirect_url = str(
                    "https://" + str(HttpRequest.get_host(request)) + "/api/payment/paymentstatus/")

                payment_response = client.payment_request_create(
                    amount=data['amount'],
                    purpose='Buying a ticket',
                    buyer_name=data['user'].username,
                    email=data['user'].email,
                    send_email=True,
                    redirect_url=redirect_url,
                    allow_repeated_payments=False,
                )
                print(payment_response)
                order_id = payment_response['payment_request']['id']
                tempTicket = Ticket.objects.get_or_create(user=data['user'], location=data['location'],
                                                          date=data['date'], quantity=data['quantity'], amount=data['amount'], payment_id=order_id)
            except Exception as e:
                return Response({
                    'detail': str(e)
                }, status=500)

            return render(request, 'form.html', {'payment_url': payment_response['payment_request']['longurl'], 'button': "hide-button", 'field': "disable-field"})

        return Response({
            'detail': ticket.errors
        }, status=400)
    else:
        if locationID is None:
            return render(request, 'form.html', {'button': "", 'field': ""})
        else:
            location = Location.objects.get(pk=locationID)
            print(location)
            return render(request, 'form.html', {"locationName": str(location.name), 'button': "", 'field': ""})



@api_view(['GET'])
@login_required
def index(request):
    print(request.headers)
    print(request.user)
    tickets = Ticket.objects.filter(user=request.user).values()[:]
    print(list(tickets))
    return Response({
        'tickets': tickets
    }, status=200)

tickets/templates/form.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <style>
        .formdiv {
            margin: 50px;
            display: flex;
            flex-direction: column;
            /* align-items: center;
            justify-content: center; */
        }

        .success {
            font-size: larger;
            color: chartreuse;
        }

        .error {
            font-size: larger;
            color: red;
        }

        .messages {
            text-align: center;
        }
    </style>

</head>

<body class="bg-dark">
    <div class="formdiv">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li type="none" class="{{ message.tags }}"> {{ message }} </li>
            {% endfor %}
        </ul>
        {% endif %}

        <form method="post" action="{% url 'ticket:bookTicket' %}">

            <div class="col-md-8" style="padding: 10px;color: aliceblue;">
                <label for="validationDefault01" class="form-label">Name</label>
                <input type="text" name="user" class="form-control" id="validationDefault01" placeholder="Location Name"
                    required>
            </div>
            <div class="col-md-12" style="padding: 10px;color: aliceblue;">
                <label for="validationDefault03" class="form-label">Location</label>
                <input type="text" name="location" class="form-control" id="validationDefault03" placeholder="Address"
                    required>
            </div>
            <div class="col-md-12" style="padding: 10px;color: aliceblue;">
                <label for="validationDefault02" class="form-label">Quantity</label>
                <input type="number" name="quantity" class="form-control" id="validationDefault02"
                    placeholder="Location Description" required>
            </div>
            {% csrf_token %}
            <div class="col-md-4" style="padding: 10px;color: aliceblue;">
                <label for="validationDefault01" class="form-label">Date</label>
                <input type="date" name="date" class="form-control" id="validationDefault01"
                    placeholder="Admin Username" required>
            </div>

            <div class="col-md-12" style="padding: 10px;color: aliceblue;">
                <label for="validationDefault02" class="form-label">Amount</label>
                <input type="number" name="amount" class="form-control" id="validationDefault02"
                    placeholder="Location Description" required>
            </div>
            <div class="col-12">
                <button class="btn btn-primary" type="submit">Submit form</button>
            </div>
        </form>

        <!-- <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
        </form>
        <div class="col-12">
            <button class="btn btn-primary" type="submit">Submit form</button>
        </div> -->

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</body>

</html>

tickets/templates/payment.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment</title>
</head>

<body>
    <form action="{{payment_url}}" method="GET">
        <button id="rzp-button1">Pay</button>
    </form>
</body>

</html>