locations/urls.py
from django.urls import path
from locations.views import newLocation, index

app_name = 'locations'
urlpatterns = [
    path('addlocation/', newLocation, name='newLocation'),
    path('', index, name='index')
]

server/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/auth/', include('users.urls')),
    path('api/location/', include('locations.urls')),
    path('api/ticket/', include('tickets.urls')),
    path('api/payment/', include('payment.urls')),
]

users/urls.py
from django.urls import path

from .views import (login, logout, private, refresh, register, reset_password,
                    resetpasssord, test)

urlpatterns = [
    path('login/', login),
    path('register/', register),
    path('private/', private),
    path('refresh/', refresh),
    path('reset/<str:token>/<int:userId>/', reset_password),
    path('resetPassword/', resetpasssord),
    path('logout/', logout),
    path('test/<int:testNo>/', test),
]

locations/models.py
from django.db import models
from users.models import User

# Create your models here.


def image_directory_path(instance, fileName):
    return 'locationImages/{0}/{1}/{2}'.format(instance.name, instance.admin.id, fileName)


class Location(models.Model):
    name = models.CharField(max_length=50, unique=True, null=False)
    address = models.CharField(max_length=500, unique=True, null=False)
    description = models.CharField(max_length=1500, null=False)
    admin = models.ForeignKey(User, on_delete=models.CASCADE)
    images = models.ImageField(upload_to=image_directory_path, max_length=100)
    status = models.BooleanField(null=False, default=False)

    def __str__(self) -> str:
        return self.name

locations/forms.py
# from django.forms import ModelForm
# from .models import location


# class locationForm(ModelForm):
#     class Meta:
#         model = location
#         fields = ['name', 'address', 'description',
#                   'admin', 'images', 'status']

locations/views.py
from django.shortcuts import render
from django.contrib import messages
from users.models import User
from rest_framework.decorators import api_view
from users.models import User
from .models import Location
from rest_framework.response import Response
from .serializers import LocationSerializer
import json
from django.core.serializers.json import DjangoJSONEncoder

# Create your views here.

# remove GET request


@api_view(['POST'])
def newLocation(request):
    if request.method == "POST":
        try:
            adminusername = request.POST.get('locationAdmin')
            admin = User.objects.get(username=adminusername)
            data = {
                'name': request.POST.get('locationName'),
                'address': request.POST.get('locationAddress'),
                'description': request.POST.get('locationDescription'),
                'images': request.FILES.get('locationImg'),
                'admin': admin.pk,
                'status': request.POST.get('locationStatus')
            }
            print(data)

        except Exception as e:
            return Response({
                'detail': "Either field name is wrong or locationAdmin is not registered -> Specific error is :" + str(e)
            }, status=400)

        location = LocationSerializer(data=data)

        if location.is_valid():
            data['admin'] = admin
            print(data)
            try:
                newlocation = Location(name=data['name'], address=data['address'],
                                       description=data['description'], admin=data['admin'], images=data['images'], status=data['status'])
                newlocation.save()
                return Response({
                    'detail': 'Location added successfully'
                }, status=200)
            except Exception as e:
                return Response({
                    'detail': "Error while saving the location in the database -> Specific error is : " + str(e)
                }, status=500)
        else:
            return Response({
                'detail': location.errors
            }, status=400)

    else:
        return render(request, 'locationform.html')


@api_view(['GET'])
def index(request):
    try:
        locations = Location.objects.all().values()
        print(locations)
        return Response({
            # 'locations': json.dumps(list(locations), cls=DjangoJSONEncoder)
            'locations': locations
        }, status=200)
    except Exception as e:
        return Response({
            'detail': str(e)
        }, status=500)

templates/locationform.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <style>
        .formdiv {
            margin: 50px;
            display: flex;
            flex-direction: column;
            /* align-items: center;
            justify-content: center; */
        }

        .success {
            font-size: larger;
            color: chartreuse;
        }

        .error {
            font-size: larger;
            color: red;
        }

        .messages {
            text-align: center;
        }
    </style>

</head>

<body class="bg-dark">
    <div class="formdiv">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li type="none" class="{{ message.tags }}"> {{ message }} </li>
            {% endfor %}
        </ul>
        {% endif %}

        <form method="post" action="{% url 'locations:newLocation' %}" enctype="multipart/form-data">

            <div class="col-md-8" style="padding: 10px;color: aliceblue;">
                <label for="validationDefault01" class="form-label">Location Name</label>
                <input type="text" name="locationName" class="form-control" id="validationDefault01"
                    placeholder="Location Name" required>
            </div>
            <div class="col-md-12" style="padding: 10px;color: aliceblue;">
                <label for="validationDefault03" class="form-label">Address</label>
                <input type="text" name="locationAddress" class="form-control" id="validationDefault03"
                    placeholder="Address" required>
            </div>
            <div class="col-md-12" style="padding: 10px;color: aliceblue;">
                <label for="validationDefault02" class="form-label">Description</label>
                <input type="text" name="locationDescription" class="form-control" id="validationDefault02"
                    placeholder="Location Description" required>
            </div>
            {% csrf_token %}
            <div class="col-md-4" style="padding: 10px;color: aliceblue;">
                <label for="validationDefault01" class="form-label">Admin Username</label>
                <input type="text" name="locationAdmin" class="form-control" id="validationDefault01"
                    placeholder="Admin Username" required>
            </div>

            <div class="col-md-4" style="padding: 10px;color: aliceblue;">
                <label for="locationImg">Select image:</label>
                <input type="file" id="img" name="locationImg" accept="image/*" required>
            </div>
            <div class="form-check" style="padding: 10px;color: aliceblue;">
                <input name="locationStatus" class="form-check-input" type="checkbox" value="True" id="invalidCheck2">
                <label class="form-check-label" for="invalidCheck2">
                    Tick if the place is currently open for visitors
                </label>
            </div>
            <div class="col-12">
                <button class="btn btn-primary" type="submit">Submit form</button>
            </div>
        </form>

        <!-- <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
        </form>
        <div class="col-12">
            <button class="btn btn-primary" type="submit">Submit form</button>
        </div> -->

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</body>

</html>

templates/reset_password.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Reset Password</title>
  <style>
    body {
      background: url("https://images.unsplash.com/photo-1581362716668-90cdec6b4882?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80");
      background-size: contain;
      overflow: hidden;
    }

    #container {
      position: absolute;
      background: #fff;
      height: 350px;
      width: 300px;
      top: 50%;
      left: 50%;
      margin-left: -150px;
      margin-top: -175px;
      box-shadow: 0px 30px 150px;
      -webkit-box-shadow: 0px 30px 150px;
      -moz-box-shadow: 0px 30px 150px;
      border-radius: 15px;
      -webkit-border-radius: 15px;
      -moz-border-radius: 15px;
    }

    #header {
      background-color: #F26B6B;
      font-family: 'Francois One', sans-serif;
      height: 75px;
      width: 300px;
      position: absolute;
      top: 0;
      color: white;
      margin-top: -2px;
      border-radius: 15px 15px 0px 0px;
      -webkit-border-radius: 15px 15px 0px 0px;
      -moz-border-radius: 15px 15px 0px 0px;
    }

    #footer.incorrect {
      background-color: #F26B6B;
      font-family: 'Francois One', sans-serif;
      height: 75px;
      width: 300px;
      position: absolute;
      bottom: 0;
      color: white;
      margin-bottom: -2px;

      border-radius: 0px 0px 15px 15px;
      -webkit-border-radius: 0px 0px 15px 15px;
      -moz-border-radius: 0px 0px 15px 15px;
    }

    #footer.correct {
      background-color: #84F075;
      font-family: 'Francois One', sans-serif;
      height: 75px;
      width: 300px;
      position: absolute;
      bottom: 0;
      color: white;
      cursor: pointer;
      margin-bottom: -2px;

      border-radius: 0px 0px 15px 15px;
      -webkit-border-radius: 0px 0px 15px 15px;
      -moz-border-radius: 0px 0px 15px 15px;
    }

    #form {
      height: 100px;
      position: absolute;
      top: 50%;
      margin-top: -50px;
      width: 75%;
      left: 50%;
      margin-left: -37.5%;
    }

    input {
      width: 215px;
      margin: 0;
      border: 0;
      border-left: 1px solid;
      border-right: 1px solid;
      outline: none;
      height: 50px;
      font-size: 20px;
      padding-left: 10px;
    }

    input#passOne {
      border-top: 1px solid;
      border-radius: 15px 15px 0px 0px;
      -webkit-border-radius: 15px 15px 0px 0px;
      -moz-border-radius: 15px 15px 0px 0px;
    }

    input#passTwo {
      border-bottom: 1px solid;
      border-top: 1px solid;
      border-radius: 0px 0px 15px 15px;
      -webkit-border-radius: 0px 0px 15px 15px;
      -moz-border-radius: 0px 0px 15px 15px;
    }

    .error {
      color: red;
    }

    .success {
      color: greenyellow;
      size: xl;
    }

    .warning {
      color: yellow;
    }
  </style>
  </head>
  
  <body>
    <div id="container">
  
      <div id="header">
        <form action="/api/auth/reset/{{token}}/{{userId}}/" method="post">
          {% csrf_token %}
          <center>
            <h1>Change Password</h1>
          </center>
          {% if messages %}
          <ul class="messages">
            {% for message in messages %}
            <li type="none" class="{{ message.tags }}"> {{ message }} </li>
            {% endfor %}
  
          </ul>
          {% endif %}
      </div>
      <div id="form">
        <input type="password" placeholder="New Password" id="passOne" name="password1" required />
        <input type="password" placeholder="Confirm Password" id="passTwo" name="password2" required />
      </div>
      <div id="footer" class="incorrect" style="display: flex; align-items: center;justify-content: center;">
        <button style="background: transparent;border: none;text-align: center;pointer-events: stroke;">
          <h1 id="footerText">Fields dont match</h1>
        </button>
      </div>
      </form>
    </div>
  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script>
      $(document).ready(function () {
        var passOne = $("#passOne").val();
        var passTwo = $("#passTwo").val();

      $("#footerText").html("Fields don't match");

      var checkAndChange = function () {
        if (passOne.length < 1) {
          if ($("#footer").hasClass("correct")) {
            $("#footer").removeClass("correct").addClass("incorrect");
            $("#footerText").html("They don't match");
          } else {
            $("#footerText").html("They don't match");
          }
        }
        else if ($("#footer").hasClass("incorrect")) {
          if (passOne == passTwo) {
            $("#footer").removeClass("incorrect").addClass("correct");
            $("#footerText").html("Continue");
          }
        }
        else {
          if (passOne != passTwo) {
            $("#footer").removeClass("correct").addClass("incorrect");
            $("#footerText").html("They don't match");
          }
        }
      }



      $("input").keyup(function () {
        var newPassOne = $("#passOne").val();
        var newPassTwo = $("#passTwo").val();

        passOne = newPassOne;
        passTwo = newPassTwo;

        checkAndChange();
      });
    });
        </script>
</body>

</html>